- name: Deploy to EC2
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_KEY }}
    script: |
      cd /home/ubuntu/autoscore
      echo "===== BEFORE PULL ====="
      git branch
      git status
      git log -1

      git pull origin main

      echo "===== AFTER PULL ====="
      git status
      git log -1

      source venv/bin/activate
      pip install -r requirements.txt
      sudo systemctl restart autoscore.service
